{
 "title": "Sistema Turnos - Obligatorio TP",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Throughput (Tráfico Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "Peticiones por segundo"
    }
   ]
  },
  {
   "title": "Latencia p95 (Velocidad)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95 Latencia"
    }
   ]
  },
  {
   "title": "Error Rate (Errores 500)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{status=~\"5..\"}[1m])",
     "legendFormat": "Errores por segundo"
    }
   ]
  }
 ]
}